clone_folder: C:\Pinvoke

image: WMF 5

install:
  - cinst pester

version: 1.0.{build}

build_script:
- ps: .\CreateModuleManifest.ps1

test_script:
- ps: .\InvokeTests.ps1

deploy_script:
- ps: .\PublishModule.ps1

environment:
  ApiKey:
    secure: jv+jb1IJtjQxAxQigSve12KwVeuu7evZk7Ot5PKapLebDyl2LHsQGcqZFQ8VeDxV